# Generated by Django 2.0.8 on 2018-09-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='City')),
                ('challenge_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Registration Code')),
            ],
        ),
    ]
