# Generated by Django 2.0.8 on 2018-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018)], default=2018, verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Stadt'),
        ),
    ]
