# Generated by Django 2.0.8 on 2018-09-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0002_auto_20180917_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='context',
            field=models.CharField(blank=True, max_length=150, verbose_name='Kontext (Schulen- / Kommunenname'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End-Datum'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start-Datum'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Registration Code'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default=2018, verbose_name='Jahr'),
        ),
    ]
