# Generated by Django 2.0.8 on 2018-09-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0002_auto_20180921_1031'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenge_code'], name='app_challen_challen_579114_idx'),
        ),
    ]
