# Generated by Django 2.0.8 on 2018-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0003_auto_20180917_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End-Datum'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start-Datum'),
        ),
    ]
