# Generated by Django 2.0.8 on 2018-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0003_auto_20180921_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_code',
            field=models.CharField(blank=True, max_length=5, unique=True, verbose_name='Challenge Code'),
        ),
    ]
