# Generated by Django 2.0.8 on 2018-09-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0004_auto_20180921_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='year',
            field=models.CharField(choices=[(2018, 2018), (2019, 2019)], default=2018, max_length=4, verbose_name='Jahr'),
        ),
    ]
