# Generated by Django 2.0.8 on 2018-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0004_auto_20180917_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Challenge Code'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='context',
            field=models.CharField(blank=True, max_length=150, verbose_name='Kontext (Schulen- / Kommunenname)'),
        ),
    ]
