# Generated by Django 2.0.8 on 2018-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0005_auto_20180917_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_code',
            field=models.CharField(blank=True, default='NZK9O9C', max_length=7, null=True, unique=True, verbose_name='Challenge Code'),
        ),
    ]
