# Generated by Django 2.0.8 on 2018-09-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0005_auto_20180922_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='year',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019)], default=2018, verbose_name='Jahr'),
        ),
    ]
