# Generated by Django 2.0.8 on 2018-10-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0007_auto_20181017_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='event_dates',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_challenges.ChallengeDates'),
        ),
    ]
