# Generated by Django 2.0.8 on 2018-10-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0008_challenge_event_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='event_dates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_challenges.ChallengeDates'),
        ),
    ]
