# Generated by Django 2.0.8 on 2018-10-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0009_auto_20181017_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='event_dates',
        ),
        migrations.AddField(
            model_name='challengedates',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_challenges.Challenge'),
        ),
    ]
