# Generated by Django 2.0.8 on 2018-10-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0011_auto_20181017_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChallengeDates',
            new_name='ChallengeDate',
        ),
    ]
