# Generated by Django 2.0.8 on 2018-10-17 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0012_auto_20181017_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='contact_info',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Ansprechpartner_in'),
        ),
    ]
