# Generated by Django 2.0.8 on 2018-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0013_auto_20181017_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengedate',
            name='event_location',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='challengedate',
            name='event_notes',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Anmerkungen'),
        ),
    ]
