# Generated by Django 2.0.8 on 2018-10-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0014_auto_20181017_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengedate',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='challengedate',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
