# Generated by Django 2.0.8 on 2018-10-17 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0016_challenge_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='contact_info',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Ansprechpartner_in'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='app_tasks.Task', verbose_name='Aufgaben'),
        ),
    ]
