# Generated by Django 2.0.8 on 2018-09-17 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='Projectname')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push notfications enabled')),
                ('project_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Registration Code')),
                ('challenge', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_challenges.Challenge')),
                ('project_creator', models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
