# Generated by Django 2.0.8 on 2018-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Projectname')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push notfications enabled')),
                ('reg_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='Registration Code')),
            ],
        ),
    ]
