# Generated by Django 2.0.8 on 2018-09-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Project Code'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code'], name='app_project_project_6aaccd_idx'),
        ),
    ]
