# Generated by Django 2.0.8 on 2018-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_auto_20180917_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Projektbeschreibung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Project Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='Projekt-Titel'),
        ),
        migrations.AlterField(
            model_name='project',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push notfications'),
        ),
    ]
