# Generated by Django 2.0.8 on 2018-09-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_auto_20180916_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='reg_code',
            new_name='project_code',
        ),
    ]
