# Generated by Django 2.0.8 on 2018-09-22 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0004_auto_20180921_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
