# Generated by Django 2.0.8 on 2018-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0006_auto_20180922_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=140, unique=True, verbose_name='Projekt-Titel'),
        ),
    ]
