# Generated by Django 2.0.8 on 2018-10-16 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0007_auto_20180922_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
