# Generated by Django 2.0.8 on 2018-09-21 10:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('task_text', models.TextField(max_length=250)),
                ('task_videolink', models.CharField(blank=True, max_length=150, null=True)),
                ('task_imagelink', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TaskMultiple',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tasks.Task')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=list, null=True, size=4)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskOpen',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tasks.Task')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskYesOrNo',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tasks.Task')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_tasks.task',),
        ),
    ]
