# Generated by Django 2.0.8 on 2018-09-17 13:54

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTaskMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_touched', models.DateTimeField(blank=True, null=True)),
                ('last_touched', models.DateTimeField(auto_now=True)),
                ('count_touched', models.PositiveIntegerField(default=0)),
                ('task_choice_key', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0)])),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_touched', models.DateTimeField(blank=True, null=True)),
                ('last_touched', models.DateTimeField(auto_now=True)),
                ('count_touched', models.PositiveIntegerField(default=0)),
                ('task_text', models.TextField(blank=True, max_length=250, null=True)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskYesOrNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_touched', models.DateTimeField(blank=True, null=True)),
                ('last_touched', models.DateTimeField(auto_now=True)),
                ('count_touched', models.PositiveIntegerField(default=0)),
                ('task_value', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('task_note', models.TextField(blank=True, max_length=250, null=True)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('task_text', models.TextField(max_length=250)),
                ('task_videolink', models.CharField(blank=True, max_length=150, null=True)),
                ('task_imagelink', models.CharField(blank=True, max_length=150, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TaskMultiple',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tasks.Task')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=list, null=True, size=4)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskOpen',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tasks.Task')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskYesOrNo',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_tasks.Task')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
            bases=('app_tasks.task',),
        ),
        migrations.AddField(
            model_name='projecttaskyesorno',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tasks.TaskYesOrNo'),
        ),
        migrations.AddField(
            model_name='projecttaskopen',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tasks.TaskOpen'),
        ),
        migrations.AddField(
            model_name='projecttaskmultiple',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tasks.TaskMultiple'),
        ),
        migrations.AlterUniqueTogether(
            name='projecttaskyesorno',
            unique_together={('project', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttaskopen',
            unique_together={('project', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='projecttaskmultiple',
            unique_together={('project', 'task')},
        ),
    ]
