# Generated by Django 2.0.8 on 2018-09-17 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskmultiple',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttaskmultiple',
            name='submitted_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttaskopen',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttaskopen',
            name='submitted_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttaskyesorno',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projecttaskyesorno',
            name='submitted_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
