# Generated by Django 2.0.8 on 2018-09-16 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projects', '0002_auto_20180916_2014'),
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_imagelink',
            new_name='task_imagelink',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='task_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_videolink',
            new_name='task_videolink',
        ),
        migrations.RenameField(
            model_name='useranswermultiple',
            old_name='question',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='useransweropen',
            old_name='question',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='useransweryesorno',
            old_name='question',
            new_name='task',
        ),
        migrations.AlterUniqueTogether(
            name='useranswermultiple',
            unique_together={('project', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='useransweropen',
            unique_together={('project', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='useransweryesorno',
            unique_together={('project', 'task')},
        ),
    ]
