# Generated by Django 2.0.8 on 2018-09-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_challenges', '0004_auto_20180921_1046'),
        ('app_projects', '0004_auto_20180921_1138'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentChallenge',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app_challenges.Challenge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='currentProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_projects.Project'),
        ),
    ]
