# Generated by Django 2.0.8 on 2018-09-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180921_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentChallenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_challenges.Challenge'),
        ),
    ]
