# Generated by Django 2.0.8 on 2018-09-23 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180923_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currentChallenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_challenges.Challenge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='currentProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_projects.Project'),
        ),
    ]
