# Generated by Django 2.0.8 on 2018-10-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_challenge_contact',
            field=models.BooleanField(default=False, verbose_name='Challenge Ansprechpartner_in'),
        ),
    ]
